M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu20.04.1} date jue 22 feb 2024 17:14:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-22T17:14:07-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X83.0Y-53.0
X83.0Y-147.0
X177.0Y-53.0
X177.0Y-147.0
M30
